feat: post and get method api and screen the values
FideCly/app pull request #281
Opened 2022-10-20 21:21 UTC by JeremyLaoo

### Changes proposed in this pull request
- cardScreen.js : Afficher via une method GET les cartes favorites du user. J'affiche ici l'url car le retour JSON ne permet pas d'afficher plus d'élément pertinent sur le shop. 
- profilScreen.js : J'ai corrigé un bug d'affichage, il ne voulait plus générer le QR code ...
- scanScreen.js : A partir du scan je récupère l'id du shop et via une method POST je l'ajoute en BDD dans les favoris du user table CARD. 

[FID-26]

2022-10-20 21:51 UTC, sihamais requested changes
Pas grand chose a modifier, je t'ai fais des suggestions que tu peux commit directement comme ça c'est plus simple pour toi.
Merci pour la description précise de la PR et son nom qui respecte la convention.

2022-10-20 21:51 UTC, sihamais commented on config/global.js
> +const defaultServer = "http://51.138.207.33:3000";
Quand t'aura le temps dans les futurs sprint on transformera ça en variable d'environment

2022-10-20 21:51 UTC, sihamais commented on screens/CardScreen.js
> +      console.log(json);
Faut enlever les `console.log` quand tu finis de tester
```suggestion
```

2022-10-20 21:51 UTC, sihamais commented on screens/CardScreen.js
> +  // const [shopId, setShopId] = useState([]);
Faut enlever les bouts de code qui sont pas utilisés
```suggestion
```

2022-10-20 21:51 UTC, sihamais commented on screens/CardScreen.js
> +  // };
Faut enlever les bouts de code qui sont pas utilisés
```suggestion
```

2022-10-20 21:51 UTC, sihamais commented on screens/CardScreen.js
> +    // getNameShop();
Faut enlever les bouts de code qui sont pas utilisés
```suggestion
```

2022-10-20 21:51 UTC, sihamais commented on screens/ScanScreen.js
> +    console.log(endAtDate);
Faut enlever les `console.log` quand on finit de tester
```suggestion
```

2022-10-21 07:15 UTC, JeremyLaoo commented on config/global.js
> +const defaultServer = "http://51.138.207.33:3000";
Ok pour plus tard

2022-10-21 07:15 UTC, JeremyLaoo commented on screens/CardScreen.js
> +  //     .then((response) => response.json())
done

2022-10-21 07:16 UTC, JeremyLaoo commented on screens/CardScreen.js
> +    const color = item.id === selectedId ? "white" : "black";
done

2022-10-21 07:16 UTC, JeremyLaoo commented on screens/CardScreen.js
> +        backgroundColor={{ backgroundColor }}
done

2022-10-21 07:16 UTC, JeremyLaoo commented on screens/CardScreen.js
> +  };
done

2022-10-21 09:33 UTC, sihamais submitted a review, later dismissed
Super, merci !

2022-10-21 13:18 UTC, sihamais approved these changes

2022-11-25 19:14 UTC, sihamais approved these changes
Juste une faute de frappe, je t'ai fais une suggestion pour la corriger. Tu peux appliquer la suggestion et ensuite merger.

2022-11-25 19:14 UTC, sihamais commented on screens/LoginScreen.js
> +            screen: "Profil",
```suggestion
            screen: "Profile",
```

2022-12-05 21:07 UTC, sihamais approved these changes

2022-12-06 20:33 UTC, merged