(feat) Init project to main
FideCly/app pull request #3
Opened 2022-07-15 08:19 UTC by JeremyLaoo

2022-07-15 08:38 UTC, sihamais requested changes
Fais gaffe t'a du texte en anglais dans l'app mais le nom des routes est en français

2022-07-15 08:38 UTC, sihamais commented on screens/ScanScreen.js
> +            onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
Je sais pas si c'est voulu, si `scanned == true` tu apelle `onBarCodeScanned` avec `undefined` ?

2022-07-15 08:38 UTC, sihamais commented on screens/ScanScreen.js
> +              <Text style={{color: 'white', fontSize:18}}>Scanne à nouveau</Text>
```suggestion
              <Text style={{color: 'white', fontSize:18}}>Scanner à nouveau</Text>
```

2022-07-15 08:44 UTC, sihamais commented on screens/ScanScreen.js
> +              <Text style={{color: 'white', fontSize:18}}>Scanne à nouveau</Text>
:warning: là c'est en français alors que plus haut les messages sont en anglais

2022-07-15 08:46 UTC, sihamais commented on App.js
> +        <Tab.Screen name="Profil" component={ProfilScreen} />
Le nom des pages est en français, choisis une langue pour toute l'app

2022-08-03 20:07 UTC, JeremyLaoo commented on screens/ScanScreen.js
> +            onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
Ok je change pour false

2022-08-03 20:09 UTC, JeremyLaoo commented on screens/ScanScreen.js
> +              <Text style={{color: 'white', fontSize:18}}>Scanne à nouveau</Text>
Ok je passe tous les messages en français

2022-08-03 20:10 UTC, sihamais requested changes

2022-08-03 20:10 UTC, sihamais commented on screens/MapScreen.js
> +      console.log("First localisation:",location);
Est-ce que le console.log est voulu ou c'était juste pour debug? Si c'est juste pour debug tu peux l'enlever

2022-08-03 20:10 UTC, sihamais commented on screens/MapScreen.js
> +          // }}
Besoin de ça ? Faut enlever le code commenté quand il est plus utilisé, c'est plus propre

2022-08-03 20:10 UTC, sihamais commented on screens/ScanScreen.js
> +        <Text>Autorisation nécessaire pour accéder à la caméra</Text>
```suggestion
        <Text>L'application nécessite une autorisation pour accéder à la caméra</Text>
```
C'est + friendly

2022-08-03 20:10 UTC, JeremyLaoo commented on App.js
> +        <Tab.Screen name="Profil" component={ProfilScreen} />
ah j'ai encore modifié avec le nouveau push, Accueil / Map / Scan QR Code / Wallet / Profil
mais wallet je trouve ca plus stylé que Portefeuille, je sais pas ce que t'en pense

2022-08-03 20:11 UTC, JeremyLaoo commented on screens/MapScreen.js
> +      console.log("First localisation:",location);
Oui debug désolé oublié de l'enlever

2022-08-03 20:12 UTC, sihamais commented on screens/ScanScreen.js
> +              <Text style={{color: 'white', fontSize:18}}>Scanne à nouveau</Text>
@JeremyLaoo Les deux lignes rouge et verte dans mon message c'est une suggestion, tu peux cliquer sur le bouton `commit suggestion` si tu veux appliquer mon changement. Le code passera de la ligne rouge à la ligne verte. C'est plus simple que de devoir commit depuis le repo

2022-08-03 20:12 UTC, JeremyLaoo commented on screens/MapScreen.js
> +          // }}
Okkk je l'avais mis au cas ou si on a besoin de prendre sa position si il se déplace mais pour l'instant je n'en avait pas besoin

2022-08-03 20:13 UTC, JeremyLaoo commented on screens/ScanScreen.js
> +        <Text>Autorisation nécessaire pour accéder à la caméra</Text>
Je suis d'accord

2022-08-03 20:14 UTC, sihamais commented on App.js
> +        <Tab.Screen name="Profil" component={ProfilScreen} />
Je préfère aussi. Mais c'est pas cohérent si le texte est en français. Sinon on peut tout passer en anglais. Mais notre marché est français donc je sais pas si c'est la meilleure idée. Je te laisse le choix mais faut avoir une seule langue partout dans l'app

2022-08-03 20:19 UTC, JeremyLaoo commented on App.js
> +        <Tab.Screen name="Profil" component={ProfilScreen} />
Ok

2022-08-03 20:22 UTC, sihamais commented on screens/ScanScreen.js
> +            onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
```suggestion
            onBarCodeScanned={ scanned ? handleBarCodeScanned : undefined }
```

2022-08-03 20:24 UTC, sihamais commented on screens/ScanScreen.js
> +            onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
@JeremyLaoo

2022-08-04 07:45 UTC, JeremyLaoo commented on screens/ScanScreen.js
> +            onBarCodeScanned={scanned ? undefined : handleBarCodeScanned}
done

2022-08-04 09:50 UTC, sihamais requested changes
Avec un peu de chance c'est la dernière fois que je te corrige :smile:

2022-08-04 09:50 UTC, sihamais commented on screens/ScanScreen.js
> +    console.log('Type:', type + '\nData URL QR CODE:', data);
Debug?

2022-08-04 09:50 UTC, sihamais commented on screens/ScanScreen.js
> +              <Text style={{color: 'white', fontSize:18}}>Ajouter aux Cartes Fid</Text>
```suggestion
              <Text style={{color: 'white', fontSize:18}}>Ajouter aux Cartes</Text>
```
Pas génial le "cartes fid"

2022-08-04 11:16 UTC, JeremyLaoo commented on screens/ScanScreen.js
> +    console.log('Type:', type + '\nData URL QR CODE:', data);
yes

2022-08-04 11:42 UTC, sihamais approved these changes
C'est bon pour moi

2022-08-04 11:46 UTC, merged